--luacheck: globals std self globals read_globals files

std = "lua51"
self = false
globals = {
    window = {
        fields = {
            scene = {
                fields = {
                    "child",
                    "prepend",
                    "untag",
                    "replace",
                    "action",
                    "hidden",
                    "child_pairs",
                    "remove_all",
                    "all",
                    "num_children",
                    "recursion_limit",
                    "remove",
                    "tag",
                    "late_action",
                    "append",
                    "cancel",
                    "paused"
                }
            },
            "active_touches",
            "bottom",
            "clear_color",
            "close",
            "height",
            "key_down",
            "key_pressed",
            "key_released",
            "keys_down",
            "keys_pressed",
            "keys_released",
            "left",
            "letterbox",
            "lock_pointer",
            "mode",
            "mouse_delta",
            "mouse_down",
            "mouse_norm_delta",
            "mouse_norm_position",
            "mouse_pixel_delta",
            "mouse_pixel_position",
            "mouse_position",
            "mouse_pressed",
            "mouse_released",
            "mouse_wheel_delta",
            "mouse_wheel",
            "pixel_height",
            "pixel_width",
            "projection",
            "resized",
            "right",
            "scene",
            "show_cursor",
            "stencil_clear_value",
            "top",
            "touch_active",
            "touch_began",
            "touch_delta",
            "touch_ended",
            "touch_force_available",
            "touch_force",
            "touch_norm_delta",
            "touch_norm_position",
            "touch_pixel_delta",
            "touch_pixel_position",
            "touch_position",
            "touches_began",
            "touches_ended",
            "width"
        }
    }
}

read_globals = {
    am = {
        fields = {
            "controller_button_released",
            "version",
            "parallel",
            "delta_time",
            "line",
            "ubyte_array",
            "ushort_norm_array",
            "audio_buffer",
            "init_gamecenter",
            "float_array",
            "translate",
            "cull_sphere",
            "perf_stats",
            "decode_png",
            "struct_array",
            "submit_gamecenter_score",
            "load_audio",
            "language",
            "controllers_attached",
            "sprite",
            "controller_button_down",
            "vec4_array",
            "short_array",
            "controller_rstick_pos",
            "byte_norm_array",
            "base64_decode",
            "short_norm_array",
            "eval_js",
            "series",
            "controller_attached",
            "sfxr_synth",
            "controller_rt_val",
            "framebuffer",
            "controller_lstick_pos",
            "load_script",
            "circle",
            "uint_norm_array",
            "depth_test",
            "bind",
            "uint_array",
            "ushort_elem_array",
            "vec2_array",
            "billboard",
            "use_program",
            "to_json",
            "loop",
            "frame_time",
            "group",
            "current_time",
            "texture2d",
            "controller_present",
            "quads",
            "encode_png",
            "load_image",
            "load_buffer",
            "particles2d",
            "buffer",
            "program",
            "image_buffer",
            "load_bitmap_font",
            "wrap",
            "load_string",
            "postprocess",
            "read_uniform",
            "window",
            "lookat",
            "show_gamecenter_leaderboard",
            "viewport",
            "platform",
            "cull_face",
            "color_mask",
            "text",
            "draw",
            "rect",
            "gamecenter_available",
            "load_obj",
            "rotate",
            "glob",
            "controller_button_pressed",
            "scale",
            "transform",
            "blend",
            "int_norm_array",
            "int_array",
            "byte_array",
            "ushort_array",
            "stencil_test",
            "controllers_present",
            "ubyte_norm_array",
            "parse_json",
            "controller_lt_val",
            "controller_detached",
            "base64_encode",
            "controllers_detached",
            "delay",
            "vec3_array",
            "tween",
            "wait",
            "uint_elem_array",
            "submit_gamecenter_achievement",
            "play",
            ease = {
                fields = {
                    "linear",
                    "quadratic",
                    "cubic",
                    "hyperbola",
                    "sine",
                    "windup",
                    "elastic",
                    "bounce",
                    "cubic_bezier",
                    "out",
                    "inout"
                }
            }
        }
    },
    math = {
        fields = {
            "oblique",
            "perspective",
            "fract",
            "scale4",
            "slerp",
            "distance",
            "randvec3",
            "simplex",
            "mix",
            "perlin",
            "dot",
            "lookat",
            "randvec4",
            "rotate4",
            "translate4",
            "ortho",
            "cross",
            "inverse",
            "sign",
            "length",
            "clamp",
            "randvec2",
            "normalize"
        }
    },
    table = {
        fields = {
            "merge",
            "keys",
            "append",
            "remove_all",
            "search",
            "filter",
            "shuffle",
            "tostring",
            "values",
            "deep_copy",
            "count",
            "clear",
            "shallow_copy"
        }
    },
    [1] = "vec4",
    [2] = "quat",
    [3] = "mat4",
    [4] = "noglobals",
    [5] = "vec3",
    [6] = "log",
    [7] = "mat2",
    [8] = "following easing functions are pre-defined ",
    [9] = "mat3",
    [10] = "vec2"
}

files["conf.lua"] = {
    globals = {
        "title",
        "shortname",
        "author",
        "appid",
        "version",
        "support_email",
        "display_name",
        "dev_region",
        "supported_languages",
        "icon",
        "launch_image",
        "orientation"
    }
}
